### PR TITLE
llama-index-llms-anthropic must be < 0.9.0 to work with llama-index-core 0.13.6

### PR DESCRIPTION
**Pull request by ruthgrace**
Otherwise it tries to import ThinkingBlock which is only available in llama-index-core 14, but llama-index-core 14 is not compatible with the rest of the droidrun codebase yet:

```
./venv/bin/droidrun --debug --provider "$PROVIDER" --model "$MODEL" "please look at the screen and tell me the coordinates of the Sign in with Google yellow button"
╭─ Activity Log (4 entries) ──────────────────────────────────────────────────────────────────────────╮
╭─ Activity Log (28 entries) ─────────────────────────────────────────────────────────────────────────╮
│ INFO droidrun 🚀 Starting: please look at the screen and tell me the coordinates of the Sign in     │
│ with Google yellow button                                                                           │
│ INFO droidrun 🕵️  Anonymized telemetry enabled. See https://docs.droidrun.ai/v3/guides/telemetry for │
│ more information.                                                                                   │
│ INFO droidrun 🔍 Finding connected device...                                                        │
│ INFO droidrun 📱 Using device: 47201FDJH002SV                                                       │
│ DEBUG droidrun-tools DroidRun keyboard setup completed                                              │
│ DEBUG droidrun Attempting to import module: llama_index.llms.anthropic                              │
│ ERROR droidrun 💥 Setup error: cannot import name 'ThinkingBlock' from                              │
│ 'llama_index.core.base.llms.types'                                                                  │
│ (/Users/ruthgracewong/droidrun/venv/lib/python3.12/site-packages/llama_index/core/base/llms/types.p │
│ y)                                                                                                  │
│ DEBUG droidrun Traceback (most recent call last):                                                   │
│   File "/Users/ruthgracewong/droidrun/venv/lib/python3.12/site-packages/droidrun/cli/main.py", line │
│ 135, in run_command                                                                                 │
│     llm = load_llm(                                                                                 │
│           ^^^^^^^^^                                                                                 │
│   File                                                                                              │
│ "/Users/ruthgracewong/droidrun/venv/lib/python3.12/site-packages/droidrun/agent/utils/llm_picker.py │
│ ", line 53, in load_llm                                                                             │
│     llm_module = importlib.import_module(module_path)                                               │
│                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                               │
│   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py",   │
│ line 90, in import_module                                                                           │
│     return _bootstrap._gcd_import(name, package, level)                                             │
│            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                     │
│   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import                                   │
│   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load                                │
│   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked                       │
│   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked                                 │
│   File "<frozen importlib._bootstrap_external>", line 995, in exec_module                           │
│   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed                      │
│   File                                                                                              │
│ "/Users/ruthgracewong/droidrun/venv/lib/python3.12/site-packages/llama_index/llms/anthropic/__init_ │
│ _.py", line 1, in <module>                                                                          │
│     from llama_index.llms.anthropic.base import Anthropic                                           │
│   File                                                                                              │
│ "/Users/ruthgracewong/droidrun/venv/lib/python3.12/site-packages/llama_index/llms/anthropic/base.py │
│ ", line 28, in <module>                                                                             │
│     from llama_index.core.base.llms.types import ThinkingBlock as LIThinkingBlock                   │
│ ImportError: cannot import name 'ThinkingBlock' from 'llama_index.core.base.llms.types'             │
│ (/Users/ruthgracewong/droidrun/venv/lib/python3.12/site-packages/llama_index/core/base/llms/types.p │
│ y)                                                                                                  │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
│                                                                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯
                                                                                                       
                                                                                                       
╭─ Goal ──────────────────────────────────────────────────────────────────────────────────────────────╮
│ please look at the screen and tell me the coordinates of the Sign in with Google yellow button      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Status ────────────────────────────────────────────────────────────────────────────────────────────╮
│ ⚡ Error: cannot import name 'ThinkingBlock' from 'llama_index.core.base.llms.types'                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### CODE REVIEW

**Comment by ruthgrace** [comment]
pinging @Timo972 in case you didn't see this PR, and no worries if you are already incorporating this change in your own development process

**Comment by Timo972** [comment]
thanks for fixing our dependency mess <3
