### ISSUE TITLE
Error in step 'handle_llm_input': 'StopEvent' object has no attribute 'message'

### ISSUE THREAD

**Issue by pengshaoxu00fa** [droidrun/droidrun#55]
Run：
 ”droidrun "Open the settings app" --provider Ollama -u http://127.0.0.1:11434 --model deepseek-r1:14b“

Error：
 Initializing Ollama with kwargs: ['model', 'base_url', 'temperature']
 Successfully loaded and initialized LLM: Ollama
 🤖 Initializing DroidAgent wrapper...
 🧠 Initializing CodeAct Agent...
 🛠️ Parsing tool descriptions...
 │
 🔩 Found 8 tools.
 ✅ CodeActAgent initialized successfully.
 ✅ DroidAgent initialized successfully.
 🚀 Running DroidAgent to achieve goal: Open the settings app
 🔄 Direct execution mode - executing goal: Open the settings app
 🔧 Executing task: Open the settings app
 💬 Preparing chat for task execution...
 🧠 Step 1: Thinking...
 Error getting LLM response:
 Error during task execution: Error in step 'handle_llm_input': 'StopEvent' object has no attribute 'message'

Why？

**Comment by BNODE1** [comment]
I’m experiencing the same issue.
Running droidrun directly inside termux and also on Windows via ADB over WiFi.

Error:
Error during task execution: Error in step 'handle_llm_input': 'StopEvent' object has no attribute 'message'


Update:
In the meantime, I was able to run it with DeepSeek, but since it doesn’t support image processing, I had to switch to another model. I totally forgot about that limitation earlier!

**Comment by Timo972** [comment]
I spent considerable time debugging this issue today but couldn't identify any problems on our end. There are several important considerations when using Ollama:
- Ensure the device running Ollama has sufficient specifications for the LLM to respond properly
- Check for error logs from Ollama itself. For example, my MacBook with an M2 chip cannot run vision models in Ollama due to an internal Metal error
- If Ollama is running behind a proxy like Cloudflare, make sure the request timeout is configured high enough

I apologize that I can't provide more specific assistance with this particular issue, as it largely depends on your individual Ollama setup configuration.
With the enhanced logging introduced in #61, you should be able to get more detailed error messages that will help narrow down the root cause.

**Comment by johnmalek312** [comment]
Closing the issue, if the issue persists in the current or future droidrun version, consider reopening it.
